### ISSUE TITLE
Ensure all chapters receive thorough review.

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#50]
I would hate to see a situation where the first several chapters are thoroughly reviewed while the later chapters get short shrift.  It would probably be best to have at least a couple different pairs of eyes on each chapter, in addition to your own.

Feel free to use and edit this list to keep track of which chapters have been reviewed in detail, and by which reviewers, so that hopefully our collective resources can best be allocated.  The checkbox doesn't so much mean "done" as simply "more done than the others".

- [ ] **1.** `05` Introduction — @carols10cents #29, Patrick
- [x] **2.** `10` What is Software Testing? — @carols10cents #29, @sdzivanovich #49, Patrick
- [ ] **3.** `13` Why Test Software? — @carols10cents #29, Patrick
- [x] **4.** `15` Testing Basics — @carols10cents #29, @sdzivanovich #49, Patrick
- [ ] **5.** `20` Requirements — @carols10cents #29, @sdzivanovich #49
- [ ] **6.** `25` Test Plans — @carols10cents #38
- [ ] **7.** `27` Breaking Software — @carols10cents #38
- [ ] **8.** `29` A Walkthrough In Creating A Test Plan — @carols10cents #38/#54
- [ ] **9.** `30` Defects— @carols10cents #54
- [ ] **10.** `32` Smoke And Acceptance Testing — @carols10cents #55
- [ ] **11.** `33` Exploratory Testing — @carols10cents #60
- [ ] **12.** `35` Manual versus Automated Testing — @carols10cents #60
- [x] **13.** `40` An Introduction to Unit Testing — @sdzivanovich #57, @carols10cents #60 
- [ ] **14.** `41` Advanced Unit Testing — @sdzivanovich #57, @carols10cents #70
- [ ] **15.** `45` Test-Driven Development — @carols10cents #72
- [ ] **16.** `50` Writing Testable Code — @carols10cents #72
- [ ] **17.** `60` Pairwise and Combinatorial Testing — @carols10cents #73
- [ ] **18.** `67` Stochastic and Property-Based Testing — @carols10cents #73
- [ ] **19.** `70` Performance Testing — @WillEngler #19, @carols10cents #73
- [ ] **20.** `75` Security Testing — @carols10cents #80
- [ ] **21.** `87` Interacting with Stakeholders — @WillEngler #30, @carols10cents #84
- [ ] **22.** `96` Conclusion — @carols10cents #84
- [ ] **23.** `97` Testing Templates
- [ ] **24.** `98` Glossary of Terms — @carols10cents #84
- [ ] **25.** `99` Acknowledgements

**Comment by carols10cents** [comment]
Oh believe me, I want to know how this one ends :)

I made it through the defects chapter tonight.

**Comment by carols10cents** [comment]
I'm through An Introduction to Unit Testing :)

**Comment by laboon** [comment]
Updated, between you and Sheridan I think this is a thorough-enough walkthrough to be checkmarked.

**Comment by carols10cents** [comment]
Done with advanced testing! https://github.com/laboon/ebook/pull/70

**Comment by carols10cents** [comment]
Done with TDD and Writing testable code :) https://github.com/laboon/ebook/pull/72

**Comment by carols10cents** [comment]
Pairwise and Combinatorial Testing, Stochastic and Property-Based Testing, and Performance Testing covered in #73!

**Comment by carols10cents** [comment]
Security testing done - #80 !

**Comment by carols10cents** [comment]
And I'm through the whole book! #84 

Let the record also show that, while I did not submit any changes to the Smoke and Acceptance Testing chapter, i did review it and provided a suggestion for it in #55. Didn't want anyone to think I had missed a chapter!!

**Comment by laboon** [comment]
OK, we had at least two people (me and Carol) read through the whole thing.  I had a separate non-GitHub reader who has been sending me emails, although I did not edit the comment.  I think we can close this one unless anyone has any disagreements.

**Comment by timparenti** [comment]
**It shall be so.**

I'll still have some stuff for you, though, as always…
